### ISSUE TITLE
Bug report AND genuine question 

### ISSUE THREAD

**Issue by Domxoxo** [Core5570RYT/FNF-CoreDEV-Engine#6]
hello.
ive switched from Psych to CDEV a bit time ago. ive noticed alot of changes,
first of all. _how clean it is in the mod folders._
_**( and here comes the question)-**_ do **PSYCH ENGINE** mods work on **CDEV** engine?
every time i try to put them in and load mods, (in the game.) it crashes, maybe its because- when i try to install haxe, it says theres "no library," im pretty confused, lol.
the crash handler doesnt work, too! **ill attach screenshots:**
please help, i really dont know what to do.
![crashhandlererror](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/159272539/5a385c75-7ff3-412d-bc93-34788e0f6a11)
![CDEVerror](https://github.com/Core5570RYT/FNF-CDEV-Engine/assets/159272539/52d22d25-5f19-4c33-81b8-d1b01ee1ac35)

**Comment by corecathx** [comment]
### Hello! Thank you for trying out CDEV Engine :)
To answer your question... Nope, Psych Engine mods **won't work** in CDEV Engine because the way CDEV Engine handles mods is different from how does Psych Engine handles it's own mods. (CDEV Engine is not a fork of Psych Engine, btw)

Also the first image that you attached there is the Crash Handler just crashed (Yes, the Crash Handler crashes itself.) because there are no enough parameters given to the Crash Handler _(Possibly because you're trying to open the crash handler by double-clicking the cdev-crash_handler.exe file)_

The only way to make your mods work in CDEV Engine is to make a Port Version in CDEV Engine of your mod, if you need help on making mods in CDEV Engine, please visit the [CDEV Engine's Official Public Discord Server](https://discord.com/invite/w8sFmXsFpk) or try to contact me @/core5570r on Discord!

**Comment by Domxoxo** [comment]
alright, thank you so much! sorry if i wasted your time lol.
